name: 'Get the Base URL'
description: 'Get the base URL where the Github Page will be hosted'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: true
outputs:
  base_url:
    description: 'URL to deployed GitHub Pages'
